### ISSUE TITLE
关于数据集的疑问

### ISSUE THREAD

**Issue by onetance** [Zhang-xiaokun/DIMO#1]
您好，我在看代码时，有一些困难，希望能得到您的帮助

1、在utils代码中
data[0]是session，data[2]是target，请问data[1]和data[3]分别代表什么意思呢，分别是如何计算的
![image](https://github.com/Zhang-xiaokun/DIMO/assets/61740950/53648f1d-da42-400b-bf3c-ea2deef1432a)

2、在model代码中
请问frequence[2]代表什么意思，怎么计算的呢
![image](https://github.com/Zhang-xiaokun/DIMO/assets/61740950/93f0c504-be0d-4e66-969f-907ca5c27f6e)
期待您的回复

**Comment by Zhang-xiaokun** [comment]
你好，
首先欢迎关注我们的工作~
1. data[1] 是标签指明label item是否与用户交互过的商品存在共现关系，用于Counterfactual Inference；
2. data[3] 是全局共现图(Global co-occurrence graph)，用于更新商品的表示，为其注入商品共现关系；
3. frequence 存储了对于一个目标商品以共现次数决定的正例[0]或者负例[1]，以及正例对应出现的次数[2](即共现次数)，用于co-occurrence constraint，其中 [2] 在model.py文件中id_co_loss函数内，会进行归一化处理，以获得原文中公式(3)分子上的正例嵌入表示。这里[2]为负数是因为numpy的计算函数返回值的格式，后续在model中调整成了对应的正整数。

另外，以上所有数据的含义及计算方法在论文中都有描述，可以进一步参考我们的原文。

**Comment by onetance** [comment]
> 你好， 首先欢迎关注我们的工作~
> 
> 1. data[1] 是标签指明label item是否与用户交互过的商品存在共现关系，用于Counterfactual Inference；
> 2. data[3] 是全局共现图(Global co-occurrence graph)，用于更新商品的表示，为其注入商品共现关系；
> 3. frequence 存储了对于一个目标商品以共现次数决定的正例[0]或者负例[1]，以及正例对应出现的次数[2](%E5%8D%B3%E5%85%B1%E7%8E%B0%E6%AC%A1%E6%95%B0)，用于co-occurrence constraint，其中 [2] 在model.py文件中id_co_loss函数内，会进行归一化处理，以获得原文中公式(3)分子上的正例嵌入表示。这里[2]为负数是因为numpy的计算函数返回值的格式，后续在model中调整成了对应的正整数。
> 
> 另外，以上所有数据的含义及计算方法在论文中都有描述，可以进一步参考我们的原文。

感谢您的回复，请问您可以提供一下数据模态的处理代码吗，以及文中数据来源更清楚的链接。
十分感谢！
